CREATE DATABASE ICETASK3;
USE ICETASK3
GO

CREATE TABLE Tasks(
TaskID INT PRIMARY KEY IDENTITY(1, 1),
TaskName VARCHAR(50),
TaskDescription VARCHAR(200),
TaskStatus VARCHAR(20)
);
GO

SELECT * FROM Tasks;